#!/usr/bin/env python3
"""Build plugin artifacts from Jinja2 templates.

Templates live in plugin_src/templates/. Each template may declare its output
path via a {#- @output: <path> -#} directive on the first line. If absent,
falls back to the template path minus the .j2 suffix, relative to PROJECT_ROOT.

Partials (files whose basename starts with _) are skipped during discovery
but available for inclusion.

Usage:
    uv run scripts/build-plugins.py [--check]
"""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

PROJECT_ROOT = Path(__file__).parent.parent
TEMPLATE_DIR = PROJECT_ROOT / "plugin_src" / "templates"

GENERATED_MARKER = "generated by plugin_src — do not modify"

OUTPUT_DIRECTIVE_RE = re.compile(r"\{#-?\s*@output:\s*(.+?)\s*-?#\}")

COMMENT_MARKERS: dict[str, str] = {
    ".md": "yaml_frontmatter",
    ".json": "json_key",
    ".yaml": "comment_hash",
    ".yml": "comment_hash",
    ".toml": "comment_hash",
    ".sh": "comment_hash",
}


def main() -> None:
    check = "--check" in sys.argv

    context = _build_context()
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        keep_trailing_newline=True,
    )

    artifacts = _discover(env)

    if check:
        _check(artifacts, env, context)
    else:
        _generate(artifacts, env, context)


def _build_context() -> dict[str, str]:
    help_text = subprocess.run(
        ["tq", "--help"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    pyproject = PROJECT_ROOT / "pyproject.toml"
    with pyproject.open("rb") as f:
        version = tomllib.load(f)["project"]["version"]

    return {
        "help_text": help_text,
        "version": version,
    }


def _discover(env: Environment) -> list[tuple[str, Path]]:
    """Return list of (template_name, output_path) pairs."""
    artifacts: list[tuple[str, Path]] = []

    assert env.loader is not None
    for template_name in env.loader.list_templates():
        if not template_name.endswith(".j2"):
            continue
        if Path(template_name).name.startswith("_"):
            continue
        output_path = _resolve_output_path(template_name)
        artifacts.append((template_name, output_path))

    return artifacts


def _resolve_output_path(template_name: str) -> Path:
    template_file = TEMPLATE_DIR / template_name
    first_line = template_file.open().readline()
    match = OUTPUT_DIRECTIVE_RE.search(first_line)
    if match:
        return PROJECT_ROOT / match.group(1)
    return PROJECT_ROOT / template_name.removesuffix(".j2")


def _render(template_name: str, env: Environment, context: dict[str, str]) -> str:
    content = env.get_template(template_name).render(**context)
    return _inject_marker(content, template_name)


def _inject_marker(content: str, template_name: str) -> str:
    if GENERATED_MARKER in content:
        return content

    output_suffix = Path(template_name.removesuffix(".j2")).suffix
    marker_type = COMMENT_MARKERS.get(output_suffix, "comment_hash")

    if marker_type == "yaml_frontmatter":
        frontmatter = f"---\n\"@plugin_src\": \"{GENERATED_MARKER}\"\n---\n\n"
        return frontmatter + content
    elif marker_type == "json_key":
        return content
    else:
        comment = f"# {GENERATED_MARKER}\n\n"
        return comment + content


def _generate(
    artifacts: list[tuple[str, Path]], env: Environment, context: dict[str, str]
) -> None:
    for template_name, output_path in artifacts:
        rendered = _render(template_name, env, context)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered)
        sys.stdout.write(f"  wrote {output_path.relative_to(PROJECT_ROOT)}\n")


def _check(
    artifacts: list[tuple[str, Path]], env: Environment, context: dict[str, str]
) -> None:
    stale: list[Path] = []
    for template_name, output_path in artifacts:
        rendered = _render(template_name, env, context)
        if not output_path.exists():
            stale.append(output_path)
            continue
        if output_path.read_text() != rendered:
            stale.append(output_path)

    if stale:
        sys.stderr.write("stale plugin artifacts:\n")
        for p in stale:
            sys.stderr.write(f"  {p.relative_to(PROJECT_ROOT)}\n")
        sys.stderr.write("\nrun `just plugins` to update\n")
        sys.exit(1)
    else:
        sys.stdout.write("all plugin artifacts up to date\n")


if __name__ == "__main__":
    main()
